<h1 align="center"> T20 World Cup Cricket Data Pre Processing </h1>

In [113]:
#import necessary libraries
import pandas as pd
import json

<h4 style="color:white">(1) Process Match Results</h4>

In [114]:
with open('web-scraping-result-JSON/t20_wc_match_results_2024.json') as f:
    data = json.load(f)

df_match = pd.DataFrame(data[0]['matchSummary'])
df_match.head(10)

,team1,team2,winner,margin,ground,matchDate,scorecard
0,India,South Africa,India,7 runs,Bridgetown,"Jun 29, 2024",T20I # 2729
1,England,India,India,68 runs,Providence,"Jun 27, 2024",T20I # 2724
2,Afghanistan,South Africa,South Africa,9 wickets,Tarouba,"Jun 26, 2024",T20I # 2723
3,Afghanistan,Bangladesh,Afghanistan,8 runs,Kingstown,"Jun 24, 2024",T20I # 2722
4,Australia,India,India,24 runs,Gros Islet,"Jun 24, 2024",T20I # 2721
5,West Indies,South Africa,South Africa,3 wickets,North Sound,"Jun 23, 2024",T20I # 2720
6,England,U.S.A.,England,10 wickets,Bridgetown,"Jun 23, 2024",T20I # 2719
7,Afghanistan,Australia,Afghanistan,21 runs,Kingstown,"Jun 22, 2024",T20I # 2717
8,Bangladesh,India,India,50 runs,North Sound,"Jun 22, 2024",T20I # 2716
9,West Indies,U.S.A.,West Indies,9 wickets,Bridgetown,"Jun 21, 2024",T20I # 2713

In [115]:
df_match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team1      52 non-null     object
 1   team2      52 non-null     object
 2   winner     52 non-null     object
 3   margin     52 non-null     object
 4   ground     52 non-null     object
 5   matchDate  52 non-null     object
 6   scorecard  52 non-null     object
dtypes: object(7)
memory usage: 3.0+ KB

**Use scorecard as a match id to link with other tables**

In [116]:
df_match.rename({'scorecard': 'match_id'}, axis = 1, inplace = True)
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,India,South Africa,India,7 runs,Bridgetown,"Jun 29, 2024",T20I # 2729
1,England,India,India,68 runs,Providence,"Jun 27, 2024",T20I # 2724
2,Afghanistan,South Africa,South Africa,9 wickets,Tarouba,"Jun 26, 2024",T20I # 2723
3,Afghanistan,Bangladesh,Afghanistan,8 runs,Kingstown,"Jun 24, 2024",T20I # 2722
4,Australia,India,India,24 runs,Gros Islet,"Jun 24, 2024",T20I # 2721

**Create a match ids dictionary that maps team names to a unique match id. This will be useful later on to link with other tables**

In [117]:
match_ids_dict = {}

for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    match_ids_dict[key1] = row['match_id']
    match_ids_dict[key2] = row['match_id']

In [118]:
df_match.to_csv('T20_wc2024_dataset_cleaned_CSV/t20_wc_match_summary_2024.csv', index = False)

PermissionError: [Errno 13] Permission denied: 'T20_wc2024_dataset_cleaned_CSV/t20_wc_match_summary_2024.csv'

<h4 style="color:white">(2) Process Batting Summary</h4>

In [ ]:
with open('web-scraping-result-JSON/t20_wc_batting_summary_2024.json') as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec['battingSummary'])
  
df_batting = pd.DataFrame(all_records)
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Canada Vs Ireland,Canada,1,Aaron Johnson,c Campher b Young,14,13,3,0,107.69
1,Canada Vs Ireland,Canada,2,Navneet Dhaliwal,c Dockrell b Adair,6,10,1,0,60.00
2,Canada Vs Ireland,Canada,3,Pargat Singh,c Little b Young,18,14,2,0,128.57
3,Canada Vs Ireland,Canada,4,Dilpreet Bajwa,c & b Delany,7,9,1,0,77.77
4,Canada Vs Ireland,Canada,5,Nicholas Kirton,c Balbirnie b McCarthy,49,35,3,2,140.00
5,Canada Vs Ireland,Canada,6,Shreyas Movvaâ€,run out (McCarthy/â€ Tucker),37,36,3,0,102.77
6,Canada Vs Ireland,Canada,7,Dilon Heyliger,c Little b McCarthy,0,2,0,0,0.00
7,Canada Vs Ireland,Canada,8,Saad Bin Zafar(c),NaN,1,1,0,0,100.00
8,Canada Vs Ireland,Ireland,1,Andy Balbirnie,c & b Junaid Siddiqui,17,19,1,0,89.47
9,Canada Vs Ireland,Ireland,2,Paul Stirling(c),c â€ Movva b Gordon,9,17,1,0,52.94
10,Canada Vs Ireland,Ireland,3,Lorcan Tuckerâ€,run out (Kirton/Saad Bin Zafar),10,15,0,0,66.66

In [ ]:
df_batting['out/not_out'] = df_batting.dismissal.apply(lambda x: "not_out" if pd.isna(x) else "out")

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
298,Scotland Vs Australia,Australia,5,Marcus Stoinis,b Watt,59,29,9,2,203.44,out
276,Nepal Vs Netherlands,Nepal,7,Sompal Kami,b van Meekeren,0,5,0,0,0.00,out
500,Afghanistan Vs South Africa,Afghanistan,11,Fazalhaq Farooqi,NaN,2,2,0,0,100.00,not_out
693,India Vs England,England,7,Liam Livingstone,run out (Kuldeep Yadav/Patel),11,16,0,0,68.75,out
21,Oman Vs Namibia,Oman,5,Khalid Kail,c & b Wiese,34,39,1,1,87.17,out
332,Afghanistan Vs Australia,Afghanistan,4,Karim Janat,c David b Cummins,13,9,0,1,144.44,out
145,Afghanistan Vs Bangladesh,Bangladesh,3,Najmul Hossain Shanto(c),c Mohammad Nabi b Naveen-ul-Haq,5,5,1,0,100.00,out
172,England Vs Namibia,England,5,Moeen Ali,c Davin b Trumpelmann,16,6,0,2,266.66,out
789,P.N.G. Vs Uganda,P.N.G.,5,Hiri Hiri,lbw b Nsubuga,15,19,2,0,78.94,out
104,Bangladesh Vs Netherlands,Bangladesh,1,Tanzid Hasan,c de Leede b van Meekeren,35,26,5,1,134.61,out

In [ ]:
df_batting['dismissal'] = df_batting.dismissal.fillna("not out")
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Canada Vs Ireland,Canada,1,Aaron Johnson,c Campher b Young,14,13,3,0,107.69,out
1,Canada Vs Ireland,Canada,2,Navneet Dhaliwal,c Dockrell b Adair,6,10,1,0,60.00,out
2,Canada Vs Ireland,Canada,3,Pargat Singh,c Little b Young,18,14,2,0,128.57,out
3,Canada Vs Ireland,Canada,4,Dilpreet Bajwa,c & b Delany,7,9,1,0,77.77,out
4,Canada Vs Ireland,Canada,5,Nicholas Kirton,c Balbirnie b McCarthy,49,35,3,2,140.00,out
5,Canada Vs Ireland,Canada,6,Shreyas Movvaâ€,run out (McCarthy/â€ Tucker),37,36,3,0,102.77,out
6,Canada Vs Ireland,Canada,7,Dilon Heyliger,c Little b McCarthy,0,2,0,0,0.00,out
7,Canada Vs Ireland,Canada,8,Saad Bin Zafar(c),not out,1,1,0,0,100.00,not_out
8,Canada Vs Ireland,Ireland,1,Andy Balbirnie,c & b Junaid Siddiqui,17,19,1,0,89.47,out
9,Canada Vs Ireland,Ireland,2,Paul Stirling(c),c â€ Movva b Gordon,9,17,1,0,52.94,out
10,Canada Vs Ireland,Ireland,3,Lorcan Tuckerâ€,run out (Kirton/Saad Bin Zafar),10,15,0,0,66.66,out

In [ ]:
df_batting['match_id'] = df_batting['match'].map(match_ids_dict)
df_batting.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,match_id
0,Canada Vs Ireland,Canada,1,Aaron Johnson,c Campher b Young,14,13,3,0,107.69,out,T20I # 2644
1,Canada Vs Ireland,Canada,2,Navneet Dhaliwal,c Dockrell b Adair,6,10,1,0,60.00,out,T20I # 2644
2,Canada Vs Ireland,Canada,3,Pargat Singh,c Little b Young,18,14,2,0,128.57,out,T20I # 2644
3,Canada Vs Ireland,Canada,4,Dilpreet Bajwa,c & b Delany,7,9,1,0,77.77,out,T20I # 2644
4,Canada Vs Ireland,Canada,5,Nicholas Kirton,c Balbirnie b McCarthy,49,35,3,2,140.00,out,T20I # 2644

**Cleanup weird characters**

In [ ]:

df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('†', ''))
df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('(c)', '')) #captain

df_batting.sample(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,match_id
262,West Indies Vs South Africa,South Africa,2,Reeza Hendricks,c â€ Pooran b Russell,0,1,0,0,0.00,out,T20I # 2720
461,Canada Vs Pakistan,Canada,2,Navneet Dhaliwal,b Mohammad Amir,4,7,1,0,57.14,out,T20I # 2665
9,Canada Vs Ireland,Ireland,2,Paul Stirling,c â€ Movva b Gordon,9,17,1,0,52.94,out,T20I # 2644
192,Afghanistan Vs New Zealand,New Zealand,6,Mark Chapman,b Rashid Khan,4,7,0,0,57.14,out,T20I # 2645
220,Australia Vs England,Australia,5,Marcus Stoinis,c Brook b Jordan,30,17,2,2,176.47,out,T20I # 2650
738,Afghanistan Vs Uganda,Afghanistan,5,Gulbadin Naib,c Masaba b Kyewuta,4,5,0,0,80.00,out,T20I # 2636
68,Australia Vs Oman,Oman,8,Mehran Khan,c David b Stoinis,27,16,1,2,168.75,out,T20I # 2641
753,Namibia Vs Australia,Namibia,2,Nikolaas Davin,c Maxwell b Hazlewood,2,7,0,0,28.57,out,T20I # 2666
268,West Indies Vs South Africa,South Africa,8,Keshav Maharaj,c Joseph b Chase,2,6,0,0,33.33,out,T20I # 2720
370,South Africa Vs U.S.A.,South Africa,2,Reeza Hendricks,c Anderson b Netravalkar,11,11,0,1,100.00,out,T20I # 2708

In [ ]:
df_batting.shape

(852, 12)

In [ ]:
df_batting.to_csv('T20_wc2024_dataset_cleaned_CSV/t20_wc_bating_summary_2024.csv', index = False)

<h4 style="color:white">(3) Process Bowling Summary</h4>

In [ ]:
with open('web-scraping-result-JSON/t20_wc_bowling_summary_2024.json') as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

[{'match': 'India Vs Afghanistan',
  'bowlingTeam': 'Afghanistan',
  'bowlerName': 'Fazalhaq Farooqi',
  'overs': '4',
  'maiden': '0',
  'runs': '33',
  'wickets': '3',
  'economy': '8.25',
  '0s': '12',
  '4s': '4',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'India Vs Afghanistan',
  'bowlingTeam': 'Afghanistan',
  'bowlerName': 'Mohammad Nabi',
  'overs': '3',
  'maiden': '0',
  'runs': '24',
  'wickets': '0',
  'economy': '8.00',
  '0s': '7',
  '4s': '3',
  '6s': '0',
  'wides': '0',
  'noBalls': '0'}]

In [ ]:
df_bowling = pd.DataFrame(all_records)
print(df_bowling.shape)
df_bowling.sample(10)

(595, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
227,Sri Lanka Vs South Africa,South Africa,Keshav Maharaj,4,0,22,2,5.50,10,0,1,0,0
11,India Vs Afghanistan,India,Ravindra Jadeja,3,0,20,1,6.66,4,0,1,0,0
513,Oman Vs England,England,Adil Rashid,4,0,11,4,2.75,20,1,0,3,0
315,Pakistan Vs U.S.A.,Pakistan,Iftikhar Ahmed,1,0,10,0,10.00,2,2,0,0,0
501,India Vs South Africa,India,Axar Patel,4,0,49,1,12.25,8,5,3,2,0
72,Afghanistan Vs Bangladesh,Bangladesh,Tanzim Hasan Sakib,4,0,36,0,9.00,9,1,2,1,0
278,Canada Vs Pakistan,Canada,Jeremy Gordon,3.3,0,17,1,4.85,11,1,0,1,0
446,Namibia Vs Scotland,Namibia,Bernard Scholtz,4,0,20,1,5.00,7,1,0,0,0
58,Afghanistan Vs South Africa,Afghanistan,Gulbadin Naib,1,0,8,0,8.00,2,1,0,0,0
577,India Vs England,India,Arshdeep Singh,2,0,17,0,8.50,5,3,0,0,0

In [ ]:
df_bowling.loc[df_bowling['bowlerName'] == 'Jasprit Bumrah']

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
7,India Vs Afghanistan,India,Jasprit Bumrah,4,1,7,3,1.75,20,1,0,0,0
208,India Vs Bangladesh,India,Jasprit Bumrah,4,0,13,2,3.25,15,1,0,0,0
255,India Vs Pakistan,India,Jasprit Bumrah,4,0,14,3,3.50,15,1,0,0,0
295,U.S.A. Vs India,India,Jasprit Bumrah,4,0,25,0,6.25,14,1,1,1,0
322,India Vs Australia,India,Jasprit Bumrah,4,0,29,1,7.25,11,3,1,0,0
500,India Vs South Africa,India,Jasprit Bumrah,4,0,18,2,4.50,14,2,0,0,0
519,Ireland Vs India,India,Jasprit Bumrah,3,1,6,2,2.00,13,0,0,0,0
578,India Vs England,India,Jasprit Bumrah,2.4,0,12,2,4.50,8,1,0,0,0

In [ ]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,India Vs Afghanistan,Afghanistan,Fazalhaq Farooqi,4,0,33,3,8.25,12,4,1,2,0,T20I # 2710
1,India Vs Afghanistan,Afghanistan,Mohammad Nabi,3,0,24,0,8.00,7,3,0,0,0,T20I # 2710
2,India Vs Afghanistan,Afghanistan,Naveen-ul-Haq,4,0,40,1,10.00,9,3,2,3,0,T20I # 2710
3,India Vs Afghanistan,Afghanistan,Rashid Khan,4,0,26,3,6.50,13,3,1,0,0,T20I # 2710
4,India Vs Afghanistan,Afghanistan,Noor Ahmad,3,0,30,0,10.00,4,1,2,1,0,T20I # 2710

In [ ]:
df_bowling.to_csv('T20_wc2024_dataset_cleaned_CSV/t20_wc_bowling_summary_2024.csv', index = False)

<h4 style="color:white">(4) Process Players Information</h4>

In [ ]:
with open('web-scraping-result-JSON/t20_wc_player_info_2024.json') as f:
    data = json.load(f)

In [ ]:
df_players = pd.DataFrame(data)

print(df_players.shape)
df_players.info()

(358, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          358 non-null    object
 1   team          358 non-null    object
 2   battingStyle  358 non-null    object
 3   bowlingStyle  325 non-null    object
 4   playingRole   358 non-null    object
 5   description   175 non-null    object
 6   input         358 non-null    object
dtypes: object(7)
memory usage: 19.7+ KB

**Cleanup weird characters**

In [ ]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('(c)', ''))

df_players.head(10)

,name,team,battingStyle,bowlingStyle,playingRole,description,input
0,Travis Head,Australia,Left hand Bat,Right arm Offbreak,Top order Batter,He had made his Sheffield Shield debut at the ...,{}
1,Zeeshan Maqsood,Oman,Left hand Bat,Slow Left arm Orthodox,Opening Batter,NaN,{}
2,Kashyap Prajapati,Oman,Right hand Bat,Right arm Offbreak,Top order Batter,NaN,{}
3,Shoaib Khan,Oman,Right hand Bat,Right arm Medium,Batter,NaN,{}
4,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"In 2017 he made his first Test hundred, agains...",{}
5,Kaleemullah,Oman,Right hand Bat,Right arm Medium,Bowler,"Since then, he has become an effective and som...",{}
6,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,Hazlewood grew up with Glenn McGrath as his id...,{}
7,Bilal Khan,Oman,Left hand Bat,Left arm Medium fast,Bowler,Bilal's pace is a couple of notches under expr...,{}
8,Bilal Khan,Oman,Left hand Bat,Left arm Medium fast,Bowler,Bilal's pace is a couple of notches under expr...,{}
9,Khalid Kail,Oman,Right hand Bat,NaN,Middle order Batter,NaN,{}

In [ ]:
df_players.drop('input', axis = 1, inplace = True)

In [119]:
df_players[df_players['team'] == 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
26,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Allrounder Hardik Pandya's calling cards brisk...
27,Rishabh Pant,India,Left hand Bat,NaN,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."
28,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Allrounder Hardik Pandya's calling cards brisk...
29,Rohit Sharma,India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
30,Shivam Dube,India,Left hand Bat,Right arm Medium,Allrounder,- Shivam Dube started his IPL career in 2019 a...
31,Kuldeep Yadav,India,Left hand Bat,Left arm Wrist spin,Bowler,Kuldeep Yadav started as a fast bowler when he...
32,Ravindra Jadeja,India,Left hand Bat,Slow Left arm Orthodox,Allrounder,"Dissed when he first appeared, Ravindra Jadeja..."
33,Jasprit Bumrah,India,Right hand Bat,Right arm Fast,Bowler,Jasprit Bumrah grabbed eyeballs first with his...
35,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
36,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
38,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
39,Ravindra Jadeja,India,Left hand Bat,Slow Left arm Orthodox,Allrounder,"Dissed when he first appeared, Ravindra Jadeja..."
183,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,"Arshdeep is one of only three Indian bowlers, ..."
239,Mohammed Siraj,India,Right hand Bat,Right arm Fast,Bowler,Potential translated to performance when he wa...

In [120]:
df_players.to_csv('T20_wc2024_dataset_cleaned_CSV/t20_wc_player_info_2024.csv', index = False)